### ISSUE TITLE
Asking how to use crawled data?

### ISSUE THREAD

**Issue by z-x-x136** [washing1127/publicRepos_mnbvc#4]
I don't know what I'm getting out of num1-num2.jsonl file content for.

eg:"{\n  \"id\": 26,\n  \"node_id\": \"MDEwOlJlcG9zaXRvcnkyNg==\",\n  \"name\": \"merb-core\",\n  \"full_name\": \"wycats/merb-core\",\n  \"private\": false,\n  \"owner\": {\n    \"login\": \"wycats\",\n    \"id\": 4,\n    \"node_id\": \"MDQ6VXNlcjQ=\",\n    \"avatar_url\": \"https://avatars.githubusercontent.com/u/4?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/wycats\",\n    \"html_url\": \"https://github.com/wycats\",\n    \"followers_url\": \"https://api.github.com/users/wycats/followers\",\n    \"following_url\": \"https://api.github.com/users/wycats/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/wycats/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/wycats/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/wycats/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/wycats/orgs\",\n    \"repos_url\": \"https://api.github.com/users/wycats/repos\",\n    \"events_url\": \"https://api.github.com/users/wycats/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/wycats/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  },\n  \"html_url\": \"https://github.com/wycats/merb-core\",\n  \"description\": \"Merb Core: All you need. None you don't.\",\n  \"fork\": false,\n  \"url\": \"https://api.github.com/repos/wycats/merb-core\",\n  \"forks_url\": \"https://api.github.com/repos/wycats/merb-core/forks\",\n  \"keys_url\": \"https://api.github.com/repos/wycats/merb-core/keys{/key_id}\",\n  \"collaborators_url\": \"https://api.github.com/repos/wycats/merb-core/collaborators{/collaborator}\",\n  \"teams_url\": \"https://api.github.com/repos/wycats/merb-core/teams\",\n  \"hooks_url\": \"https://api.github.com/repos/wycats/merb-core/hooks\",\n  \"issue_events_url\": \"https://api.github.com/repos/wycats/merb-core/issues/events{/number}\",\n  \"events_url\": \"https://api.github.com/repos/wycats/merb-core/events\",\n  \"assignees_url\": \"https://api.github.com/repos/wycats/merb-core/assignees{/user}\",\n  \"branches_url\": \"https://api.github.com/repos/wycats/merb-core/branches{/branch}\",\n  \"tags_url\": \"https://api.github.com/repos/wycats/merb-core/tags\",\n  \"blobs_url\": \"https://api.github.com/repos/wycats/merb-core/git/blobs{/sha}\",\n  \"git_tags_url\": \"https://api.github.com/repos/wycats/merb-core/git/tags{/sha}\",\n  \"git_refs_url\": \"https://api.github.com/repos/wycats/merb-core/git/refs{/sha}\",\n  \"trees_url\": \"https://api.github.com/repos/wycats/merb-core/git/trees{/sha}\",\n  \"statuses_url\": \"https://api.github.com/repos/wycats/merb-core/statuses/{sha}\",\n  \"languages_url\": \"https://api.github.com/repos/wycats/merb-core/languages\",\n  \"stargazers_url\": \"https://api.github.com/repos/wycats/merb-core/stargazers\",\n  \"contributors_url\": \"https://api.github.com/repos/wycats/merb-core/contributors\",\n  \"subscribers_url\": \"https://api.github.com/repos/wycats/merb-core/subscribers\",\n  \"subscription_url\": \"https://api.github.com/repos/wycats/merb-core/subscription\",\n  \"commits_url\": \"https://api.github.com/repos/wycats/merb-core/commits{/sha}\",\n  \"git_commits_url\": \"https://api.github.com/repos/wycats/merb-core/git/commits{/sha}\",\n  \"comments_url\": \"https://api.github.com/repos/wycats/merb-core/comments{/number}\",\n  \"issue_comment_url\": \"https://api.github.com/repos/wycats/merb-core/issues/comments{/number}\",\n  \"contents_url\": \"https://api.github.com/repos/wycats/merb-core/contents/{+path}\",\n  \"compare_url\": \"https://api.github.com/repos/wycats/merb-core/compare/{base}...{head}\",\n  \"merges_url\": \"https://api.github.com/repos/wycats/merb-core/merges\",\n  \"archive_url\": \"https://api.github.com/repos/wycats/merb-core/{archive_format}{/ref}\",\n  \"downloads_url\": \"https://api.github.com/repos/wycats/merb-core/downloads\",\n  \"issues_url\": \"https://api.github.com/repos/wycats/merb-core/issues{/number}\",\n  \"pulls_url\": \"https://api.github.com/repos/wycats/merb-core/pulls{/number}\",\n  \"milestones_url\": \"https://api.github.com/repos/wycats/merb-core/milestones{/number}\",\n  \"notifications_url\": \"https://api.github.com/repos/wycats/merb-core/notifications{?since,all,participating}\",\n  \"labels_url\": \"https://api.github.com/repos/wycats/merb-core/labels{/name}\",\n  \"releases_url\": \"https://api.github.com/repos/wycats/merb-core/releases{/id}\",\n  \"deployments_url\": \"https://api.github.com/repos/wycats/merb-core/deployments\",\n  \"created_at\": \"2008-01-12T05:50:53Z\",\n  \"updated_at\": \"2023-05-11T00:05:33Z\",\n  \"pushed_at\": \"2008-10-13T02:31:34Z\",\n  \"git_url\": \"git://github.com/wycats/merb-core.git\",\n  \"ssh_url\": \"git@github.com:wycats/merb-core.git\",\n  \"clone_url\": \"https://github.com/wycats/merb-core.git\",\n  \"svn_url\": \"https://github.com/wycats/merb-core\",\n  \"homepage\": \"http://www.merbivore.com\",\n  \"size\": 3462,\n  \"stargazers_count\": 437,\n  \"watchers_count\": 437,\n  \"language\": \"Ruby\",\n  \"has_issues\": true,\n  \"has_projects\": true,\n  \"has_downloads\": true,\n  \"has_wiki\": true,\n  \"has_pages\": false,\n  \"has_discussions\": false,\n  \"forks_count\": 64,\n  \"mirror_url\": null,\n  \"archived\": false,\n  \"disabled\": false,\n  \"open_issues_count\": 13,\n  \"license\": null,\n  \"allow_forking\": true,\n  \"is_template\": false,\n  \"web_commit_signoff_required\": false,\n  \"topics\": [\n\n  ],\n  \"visibility\": \"public\",\n  \"forks\": 64,\n  \"open_issues\": 13,\n  \"watchers\": 437,\n  \"default_branch\": \"master\",\n  \"permissions\": {\n    \"admin\": false,\n    \"maintain\": false,\n    \"push\": false,\n    \"triage\": false,\n    \"pull\": true\n  },\n  \"network_count\": 64,\n  \"subscribers_count\": 5\n}\n"

If you can help me with this question, thank you very much

**Comment by washing1127** [comment]
Sorry for late response.
This is only the meta data of github repos. If you want more details, such as codes of a repo,  [this](https://github.com/imgingroot/github_downloader_mnbvc) project may give you some help.
